### ISSUE TITLE
Support for 32-bit and 16-bit precision

### ISSUE THREAD

**Issue by hakonbar** [leonbohmann/APReader#12]
Hi Leon, and thanks for putting together this library! I came across it a few weeks back when I was looking to read some catman-files into Python.
Because my measurement files were written with single precision (32-bit), I made a fork and added in this functionality ([https://github.com/hakonbar/APReader](https://github.com/hakonbar/APReader)). I don't think I'll be actively maintaining this fork, though, so feel free to merge it into your code if you like =)

**Comment by leonbohmann** [comment]
Hey man!
Thank you for your work! I also saw that you improved some of the byte packing? Could you document your code changes and create a pull request? I will happily merge it in time!

**Comment by leonbohmann** [comment]
Merged with #13

**Comment by leonbohmann** [comment]
You could also update your fork to be based on dev, so the next PR will be merged into that automatically!

**Comment by hakonbar** [comment]
Sure, I'll do that! Your master branch was a few commits ahead at the time I made the pull request so that's why I picked that one.
