### ISSUE TITLE
channel-issue

### ISSUE THREAD

**Issue by MaximilianailimixaM** [leonbohmann/APReader#14]
Everytime i want to have a view on my channels (5 in total), i get a TypeError:  __str__ returned non-string (type NoneType)
Is it possible to get a list or an array from my Channels?

**Comment by leonbohmann** [comment]
Could you post the complete stack of your issue?

**Comment by leonbohmann** [comment]
I mean the stack-trace of your error

**Comment by leonbohmann** [comment]
This might be related to changes in 0cc386658d0f8a18fd359b22249d9734ff6616cc `apreader.py` when analyzing channel data. When checking if the channel is the related time channel the name is converted to string, maybe that fails when name is empty..

**Comment by MaximilianailimixaM** [comment]
Input In [17], in <cell line: 3>()
      2 from apread.entries import Channel, Group
      3 for channel in reader.Channels:
----> 4     print(channel)

TypeError: __str__ returned non-string (type NoneType)

**Comment by MaximilianailimixaM** [comment]
Should i use an earlier Version of apreader?

**Comment by leonbohmann** [comment]
By doing that you effectively call the `__str__(self)` method on `Channel`.

How do you create the `APReader`?

**Comment by leonbohmann** [comment]
Ok I found the issue. For now, just try to print the data directly using something like this:

```python
for channel in reader.Channels:
    print(channel.Name)
    for data in channel.data:
        print(data)
```

Of course you could also use the `channel.getas('json'|'csv')` method to get a string representation of the data object...

**Comment by MaximilianailimixaM** [comment]
Thanks
i dont want to use channel.getas because i want to work with the bin-data!

**Comment by leonbohmann** [comment]
What do you mean? The bin-data is just converted into a more convenient format, if you want to. Of course you can access the raw data using the channels `data`-object.

**Comment by MaximilianailimixaM** [comment]
I want to safe the data from Catman in a Dataframe. Using the channels from apreader looked like the easiest way to do it. Saving the files as Json or CSV would use to much storage space

**Comment by leonbohmann** [comment]
Ok I see! Same thing another user is reporting. Can I close this?

**Comment by MaximilianailimixaM** [comment]
yes, thanks for your help!

**Comment by leonbohmann** [comment]
You're welcome!
