### ISSUE TITLE
External Heder

### ISSUE THREAD

**Issue by MaximilianailimixaM** [leonbohmann/APReader#16]
Hello,
I have a Problem with the External Header. I want to use exthdr['PhysUnit'] to get a list of the Channel_Units or add a row of Units to my DataFrame. But i am not sure how to implement it to my code!
(Btw thank you for your awesome library, it really helped me a lot with my project!)

My Code:
reader = APReader(m_file_path)

col = []                       
for channel in reader.Channels:
    col.append(channel.Name)

rows =[]                         
for channel in reader.Channels:  
    rows.append(channel.data)    

unit = []
for channel in reader.ExtHeader:
    unit.append(channel.exthdr['PhysUnit'])

df = pd.DataFrame(rows)          #Erstellung des Dataframes/ Einlesen der Rows in den DataFrame
df = df.T                        #Die Rows werden mit dem Columns geswaped, da diese Vertauscht waren
df.columns = col 

AttributeError: 'APReader' object has no attribute 'ExtHeader'

**Comment by leonbohmann** [comment]
You are iterating over `reader.ExtHdr`,the APReader does not have such a property. You have to foreach over reader.Channels, just like you did in the first two loops.

**Comment by MaximilianailimixaM** [comment]
If i loop over reader.Channels i get an AttributeError (AttributeError: 'Channel' object has no attribute 'ExtHdr')

unit = []
for channel in reader.Channels:
    unit.append(channel.ExtHdr['PhysUnit'])

**Comment by leonbohmann** [comment]
The property you are looking for is:

```
channel.extHeader
```

**Comment by MaximilianailimixaM** [comment]
`unit = []`
`for channel in reader.Channels:`
    `unit.append(channel.extHeader['PhysUnit'])`

This does not work for me... Do i need to use the binaryreader when i load the data?

**Comment by leonbohmann** [comment]
What does not work for you? What is the issue?

**Comment by MaximilianailimixaM** [comment]
AttributeError: 'Channel' object has no attribute 'extHeader'

**Comment by leonbohmann** [comment]
Make sure you use the current version! Run

```
pip install --upgrade apread
```

**Comment by MaximilianailimixaM** [comment]
It works now! Thank you!
