### ISSUE TITLE
External Header # timestamp format

### ISSUE THREAD

**Issue by PTR13** [leonbohmann/APReader#17]
Hi!

I am trying to get the date from the timestamp, but I do not understand the format. 

I have tried:

from apread import APReader
from datetime import datetime

reader = APReader(filename)
timestamp = reader.Channels[0].extHeader["T0"]
date = datetime.fromtimestamp(timestamp)

print(timestamp)
print(date)

44740.495729166665
1970-01-01 13:25:40.495729

I should be getting:
2022-06-28 11:53:50

Could you help me understanding the format?
Thanks a lot in advance!

**Comment by leonbohmann** [comment]
I will have a look this afternoon, until then, have a look in the excel sheet in test folder. There the external header is explained.

**Comment by leonbohmann** [comment]
I had a look and it seems like the timestamp uses the serial format. ([see SO](https://stackoverflow.com/questions/6706231/fetching-datetime-from-float-in-python)).

The conversion would look like this:
```python
excelTime = timestamp
realtimestamp = (excelTime - 25569) * 86400.0
datetime = datetime.utcfromtimestamp(realtimestamp )
```

Hope this helps!

**Comment by PTR13** [comment]
Now everything is clear!

Thanks a lot!!!!

**Comment by leonbohmann** [comment]
Another thing: Each channel has a time property as well! So instead of

```python
timestamp = reader.Channels[0].extHeader["T0"]
```
you should use:
```python
timestamp = reader.Channels[0].time
```

I will include a default conversion of the timestamp to datetime in the next release.
