### ISSUE TITLE
Groups.Channels

### ISSUE THREAD

**Issue by Yurnerosk** [leonbohmann/APReader#22]
Hello, I'd like to know if there is any way of first filtering by groups, and then, by channels?

What I wanted to do is:
```
for group in reader.Groups:
         print("this group has channels:")
         for channels in group.Channels:
                    print(channel)
```

**Comment by Yurnerosk** [comment]
If there is not, could I try to create it?

**Comment by leonbohmann** [comment]
Hi,You can of course filter the group, before further analyzing it. Then continue, if it does not fit your criteria. For example, check for regex matches in the name.For direct name filtering there currently only is the channel method on groups. If you know the number beforehand, there is also a function on the reader that can return certain groups by their indice number.BestLeonAm 19.09.2024 15:21 schrieb Yurner0 ***@***.***>:
If there is not, could I try to create it?

**Comment by Yurnerosk** [comment]
I didn't notice I could just use the following:
```
for group in reader.Groups:
    df = pd.DataFrame()
    print(group.Name)
    for channel in group.Channels:
        print(channel.Name)
        df[channel.Name] = channel[:]
```

Thanks a lot!
